# structure to hold orbital data

define	LEN_ORB		20
define	EPCHTIME	Memd[$1]
define	SDMEANAN	Memd[$1+1]
define	CIRVELOC	Memd[$1+2]
define	COSINCLI	Memd[$1+3]
define	ECCENTRY	Memd[$1+4]
define	ECCENTX2	Memd[$1+5]
define	ECBDX4D3	Memd[$1+6]
define	ESQDX5D2	Memd[$1+7]
define	ECBDX3		Memd[$1+8]
define	FDMEANAN	Memd[$1+9]
define	RCASCNRV	Memd[$1+10]
define	ARGPERIG	Memd[$1+11]
define	MEANANOM	Memd[$1+12]
define	RCARGPER	Memd[$1+13]
define	RASCASCN	Memd[$1+14]
define	SINEINCL	Memd[$1+15]
define	SEMILREC	Memd[$1+16]
define	PSANGLV3	Memd[$1+17]
define	RTASCNV1	Memd[$1+18]
define	DECLNV1		Memd[$1+19]
