+-----------------------------------------------------------------------+
|                This is the STSDAS playpen package			|
|								 	| 
|   It consists of prototype tasks that may be undergoing development	|
|   and  testing,  or tasks that do not fit conveniently into another	|
|   package.  Be aware that parmeter lists and operation of tasks may	|
|   change.   Some  tasks may move to another package.  Questions may	|
|   be  directed  to  STSDAS  staff  through  the   "HotSeat".    The	|
|   stsdas.contrib package contains software contributed from outside	|
|   the STSDAS project.							|
|									|
+-----------------------------------------------------------------------+
