# HCHECK.H -- Symbolic constants used by hcheck

define SYNTAX		1	# Syntax errors in evexpr
define MISSING		2	# Keyword missing
define LOCAL		3	# Other errors generated by this task

define NEVER		0	# Never print these keywords
define ALWAYS		1	# Always print these keywords
define IF_MISSING	2	# Print the keywords if missing
define IF_TRUE		3	# Print these keywords if expression is true

define SZ_KEYWORD	8	# Maximum length of header keyword

define NFUNC		9	# Number of task supplied functions
define TY_SAME		-1	# All arguments must be of same arbitrary type

define FSTRING		"match,isbool,ischar,isint,isreal,islower,isupper,\
tolower,toupper"		# Names of task supplied functions

