# allowed calibrations
define	CALIB	"|BPIXTAB|MOFFTAB|MLINTAB|ATODTAB|CCDTAB|\
BIASFILE|CRREJTAB|DARKFILE|APDESTAB|PFLTFILE|DFLTFILE|LFLTFILE|\
SHADFILE|PHOTTAB|IDCTAB|SDCTAB|XTRACTAB|SPTRCTAB|LAMPTAB|\
DISPTAB|INANGTAB|APERTAB|SDSTFILE|PCTAB|WBIAFILE|"

define	BPIXTAB		1
define	MOFFTAB		2
define	MLINTAB		3
define	ATODTAB		4
define	CCDTAB		5

define	BIASFILE	6
define	CRREJTAB	7
define	DARKFILE	8
define	APDESTAB	9
define	PFLTFILE	10
define	DFLTFILE	11
define	LFLTFILE	12

define	SHADFILE	13
define	PHOTTAB		14
define	IDCTAB		15
define	SDCTAB		16
define	XTRACTAB	17
define	SPTRCTAB	18
define	LAMPTAB		19

define	DISPTAB		20
define	INANGTAB	21
define	APERTAB		22
define	SDSTFILE	23
define	PCTAB		24
define	WBIAFILE	25

define	NREF		30

define	MAX_SUMMARY	7

define STATFLAG		1
define DOPPCORR		2
define DQICORR		3
define LFLGCORR		4
define LORSCORR		5
define GLINCORR		6
define ATODCORR		7
define BLEVCORR		8
define BIASCORR		9
define CRCORR		10
define EXPSCORR		11
define DARKCORR		12
define BACKCORR		13
define FLATCORR		14
define SHADCORR		15
define PHOTCORR		16
define GEOCORR		17
define X2DCORR		18
define X1DCORR		19
define WAVECORR		20
define DISPCORR		21
define HELCORR		22
define FLUXCORR		23
define RPTCORR		24
define SGEOCORR		25
