task	crrej	    = t_crrej,
	bjdetect    = t_bjdetect,
	combine	    = t_combine,
	engextr	    = t_engextr,
	invmetric   = t_invmetric,
	t_metric    = t_metric,
	mkdark      = t_mkdark,
	noisemodel  = t_noisemodel,
	pixcoord    = t_pixcoord,
	qmosaic     = t_qmosaic,
	seam	    = t_seam,
	uchscale    = t_uchscale,
	uchcoord    = t_uchcoord,
	t_warmpix   = t_warmpix,
	wfixup	    = t_wfixup,
	wmosaic     = t_wmosaic,
	wstatistics = t_wstatistics

