+---------------------------------------------------------------------+
|                This is the STSDAS contrib package		      |
|								      | 
|  This package contains tasks that are user-contributed, and as such,|
|  are not supported by the STSDAS group.  These tasks are provided as|
|  received as a service to the user community.   	              |
|								      |
|  Use at your own risk.				   	      |
|								      |
+---------------------------------------------------------------------+
